# Copyright 2024 Gennaro Gambardella.
# This is used to build the honey_tool slim release docker image.
# It can also be used to build local images, especially if you've made changes
# to the code.
# Example command:
# $ git clone https://github.com/gambalab/honey_pipes
# $ cd honey_pipes
# $ sudo docker build -f ./Dockerfile_slim -t honey_tools_slim .

FROM continuumio/miniconda3 AS conda_setup
RUN conda config --add channels defaults && \
    conda config --add channels bioconda && \
    conda config --add channels conda-forge
RUN conda create -y -n bio \
                    bioconda::bcftools=1.20 \
                    bioconda::samtools=1.20 \
                    bioconda::tabix=0.2.6 \
                    bioconda::sambamba=1.0.1 \
		            bioconda::bbmap=39.06 \
                    && conda clean -a

RUN conda create -y -n pod5 \
    && conda init \
    && . ~/.bashrc \
    && conda activate pod5 \
    && conda install -y pip \
    && pip install pod5 \
    && conda deactivate \
    && conda clean -a

FROM ubuntu:24.04 AS builder

COPY --from=conda_setup /opt/conda /opt/conda

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential \
        libboost-all-dev \
        libgtest-dev && \
        apt-get autoremove && \
        apt-get clean && \
    rm -rf /var/lib/apt/lists

# Include dorado
WORKDIR /tmp/
RUN 

# Copying DRAGMAP source code and build
COPY ./DRAGMAP /opt/dragmap_src
ENV HAS_GTEST=0
ENV STATIC=1
WORKDIR /opt/dragmap_src
RUN make -j4

# Copying minimap2 source code and build
COPY ./minimap2 /opt/minimap_src
WORKDIR /opt/minimap_src
RUN make -j4

# Copy bin files
WORKDIR /opt/bin
COPY ./scripts/*.sh .
RUN cp /opt/dragmap_src/build/release/dragen-os .
RUN cp /opt/dragmap_src/build/release/compare .
RUN cp /opt/minimap_src/minimap2 .
RUN chmod +x /opt/bin/*

# clea files
RUN rm -rf /opt/minimap_src /opt/dragmap_src/

ENV PATH="${PATH}":/opt/conda/bin:/opt/conda/envs/bio/bin:/opt/conda/envs/pod5/bin:/opt/bin
